# Generated by Django 4.2.6 on 2023-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='country',
        ),
    ]
